name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./installers/requirements.txt

      - name: Download and setup ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -q -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip -o /tmp/chromedriver.zip -d /tmp

      - name: Set up xvfb and run test CTpositivo
        continue-on-error: true
        run: |
          export DISPLAY=:99
          xvfb-run --server-args="-screen 0 1920x1080x24" python -m robot --argumentfile ./tests/args-positivo.txt ./tests/CTpositivo-form.robot

      - name: Set up xvfb and run test CTnegativo
        continue-on-error: true
        run: |
          export DISPLAY=:99
          xvfb-run --server-args="-screen 0 1920x1080x24" python -m robot --argumentfile ./tests/args-negativo.txt ./tests/CTnegativo-form.robot

      - name: Upload test reports
        if: always()  # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            /home/runner/work/automation-practice-form/automation-practice-form/output.xml
            /home/runner/work/automation-practice-form/automation-practice-form/log.html
            /home/runner/work/automation-practice-form/automation-practice-form/report.html
